FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Add non-root user
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nextjs -u 1001 -G nodejs
USER nextjs

EXPOSE 3000

CMD ["npm", "run", "dev"]
